### PR TITLE
Allow logging the result in DeferredContext.

### LINKED ISSUE #169: Allow DeferredContext.addActionFinish to record the result.
Perhaps by specifying the key to log to?

This is particularly useful, since there isn't an easy way to call a function in a callback, without disturbing the response. (https://twistedmatrix.com/trac/ticket/6292)

### PR DESCRIPTION
**Pull request by tomprince**
Fixes #169.

### CODE REVIEW

**Comment by itamarst** [comment]
Oh. Huh. So the idea is to add the value currently inside the Deferred as a success field. Good idea, I've definitely struggled with that once or twice.

But... what if there's multiple values you want to use as multiple fields? Perhaps the argument should be a function that takes the Deferred result (without affecting it) and returns a dictionary?

```
dc = DeferredContext(d)
dc.addActionFinish(lambda result: {u"key": result.key, u"another": result.another})
```

Also could use some docs and news entry. Address and resubmit.

**Comment by tomprince** [comment]
> what if there's multiple values you want to use as multiple fields?

I think this is best handled through addressing #16, rather than coming up with a solution that is particular to this.

**Comment by itamarst** [comment]
Relying on #16 means you're too tied to the assumption that the result of the Deferred maps directly to what you're logging, which I don't want to assume - in general idea is that logging should impact business logic code as little as possible.

**Comment by itamarst** [comment]
Going to close this since it's stalled. Please feel free to address comments and resubmit.

**Pull request closed without merging**
